// <auto-generated />
namespace WpfApp1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class orderorderitemcaritemadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(orderorderitemcaritemadded));
        
        string IMigrationMetadata.Id
        {
            get { return "202604290710466_order-order-item-caritem-added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
